ALIASES = {
    "NQ1!": "NQ=F",
    "NQ": "NQ=F",
    "ES1!": "ES=F",
    "ES": "ES=F",
    "YM1!": "YM=F",
    "YM": "YM=F",
    "RTY1!": "RTY=F",
    "RTY": "RTY=F",
    "CL1!": "CL=F",
    "CL": "CL=F",
    "BZ1!": "BZ=F",
    "BZ": "BZ=F",
    "NG1!": "NG=F",
    "NG": "NG=F",
    "GC1!": "GC=F",
    "GC": "GC=F",
    "SI1!": "SI=F",
    "SI": "SI=F",
    "HG1!": "HG=F",
    "HG": "HG=F",
    "ZC1!": "ZC=F",
    "ZC": "ZC=F",
    "ZW1!": "ZW=F",
    "ZW": "ZW=F",
    "ZS1!": "ZS=F",
    "ZS": "ZS=F",
    "KC1!": "KC=F",
    "KC": "KC=F",
    "CC1!": "CC=F",
    "CC": "CC=F",
    "SB1!": "SB=F",
    "SB": "SB=F",
    "CT1!": "CT=F",
    "CT": "CT=F",
    "LE1!": "LE=F",
    "LE": "LE=F",
    "HE1!": "HE=F",
    "HE": "HE=F",
    "ZB1!": "ZB=F",
    "ZB": "ZB=F",
    "ZN1!": "ZN=F",
    "ZN": "ZN=F",
    "ZF1!": "ZF=F",
    "ZF": "ZF=F",
    "ZT1!": "ZT=F",
    "ZT": "ZT=F",
}


ASSET_GROUPS = {
    "NASDAQ_CORE_ETFS": [
        "QQQ",
        "QQQM",
    ],
    "NASDAQ_NEXT_GEN_ETFS": [
        "QQQJ",
    ],
    "NASDAQ_INCOME_ETFS": [
        "QQQI",
        "QQQY",
        "QYLD",
        "JEPQ",
    ],
    "NASDAQ_LEVERAGED_ETFS": [
        "QLD",
        "TQQQ",
    ],
    "NASDAQ_INVERSE_ETFS": [
        "PSQ",
        "QID",
        "SQQQ",
    ],
    "FUTURES_INDICES": [
        "NQ1!",
        "ES1!",
        "YM1!",
        "RTY1!",
    ],
    "FUTURES_ENERGY": [
        "CL1!",
        "BZ1!",
        "NG1!",
    ],
    "FUTURES_METALS": [
        "GC1!",
        "SI1!",
        "HG1!",
    ],
    "FUTURES_AGRICULTURE": [
        "ZC1!",
        "ZW1!",
        "ZS1!",
        "KC1!",
        "CC1!",
        "SB1!",
        "CT1!",
        "LE1!",
        "HE1!",
    ],
    "FUTURES_RATES": [
        "ZB1!",
        "ZN1!",
        "ZF1!",
        "ZT1!",
    ],
    "US_INDEX_ETFS": [
        "SPY",
        "VOO",
        "IVV",
        "VTI",
        "ITOT",
        "SCHB",
        "DIA",
        "IWM",
        "VTWO",
        "RSP",
    ],
    "GLOBAL_ETFS": [
        "VT",
        "ACWI",
        "URTH",
        "VXUS",
        "VEA",
        "IEFA",
        "VWO",
        "IEMG",
        "SCHF",
        "SCHE",
    ],
    "STYLE_FACTOR_ETFS": [
        "IJH",
        "VO",
        "SCHM",
        "IJR",
        "VB",
        "SCHA",
        "IWF",
        "VUG",
        "SCHG",
        "IWD",
        "VTV",
        "SCHV",
        "IWO",
        "IWN",
        "VBR",
        "VBK",
        "MTUM",
        "QUAL",
        "USMV",
        "VLUE",
    ],
    "SECTOR_ETFS": [
        "XLK",
        "XLF",
        "XLV",
        "XLE",
        "XLY",
        "XLP",
        "XLI",
        "XLB",
        "XLU",
        "XLRE",
        "XLC",
        "VGT",
        "VFH",
        "VHT",
        "VDE",
        "VCR",
        "VDC",
        "VIS",
        "VAW",
        "VPU",
        "VNQ",
        "VOX",
    ],
    "THEMATIC_ETFS": [
        "SMH",
        "SOXX",
        "IGV",
        "CIBR",
        "HACK",
        "ARKK",
        "ARKQ",
        "ARKG",
        "BOTZ",
        "ROBO",
        "ICLN",
        "TAN",
        "QCLN",
        "ITA",
        "XAR",
        "KRE",
        "KBE",
        "XBI",
        "IBB",
    ],
    "BOND_ETFS": [
        "BND",
        "AGG",
        "BNDX",
        "TLT",
        "IEF",
        "SHY",
        "VGSH",
        "VGIT",
        "VGLT",
        "GOVT",
        "TIP",
        "SCHP",
        "LQD",
        "VCIT",
        "VCSH",
        "HYG",
        "JNK",
        "MUB",
    ],
    "COMMODITY_ETFS": [
        "GLD",
        "IAU",
        "SGOL",
        "SLV",
        "SIVR",
        "PDBC",
        "DBC",
        "USO",
        "BNO",
        "UNG",
        "CPER",
        "DBA",
    ],
    "DIVIDEND_ETFS": [
        "SCHD",
        "VIG",
        "VYM",
        "DGRO",
        "HDV",
        "NOBL",
    ],
    "COUNTRY_ETFS": [
        "EWJ",
        "EWG",
        "EWU",
        "EWQ",
        "EWI",
        "EWP",
        "EWL",
        "EWN",
        "EWC",
        "EWA",
        "EWH",
        "EWS",
        "EWY",
        "EWT",
        "INDA",
        "MCHI",
        "EWZ",
        "EWW",
    ],
    "MAJOR_STOCKS": [
        "AAPL",
        "MSFT",
        "NVDA",
        "AMZN",
        "GOOGL",
        "META",
        "TSLA",
        "AVGO",
        "AMD",
        "NFLX",
        "JPM",
        "BAC",
        "GS",
        "XOM",
        "CVX",
        "UNH",
        "LLY",
        "JNJ",
        "WMT",
        "COST",
        "PLTR",
        "COIN",
        "MSTR",
    ],
    "CRYPTO": [
        "BTC-USD",
        "ETH-USD",
        "SOL-USD",
        "XRP-USD",
        "ADA-USD",
        "DOGE-USD",
        "BNB-USD",
        "LINK-USD",
        "AVAX-USD",
    ],
    "FOREX": [
        "EURUSD=X",
        "GBPUSD=X",
        "USDJPY=X",
        "USDCHF=X",
        "AUDUSD=X",
        "NZDUSD=X",
        "USDCAD=X",
        "EURGBP=X",
        "EURJPY=X",
        "GBPJPY=X",
    ],
    "VOLATILITY": [
        "^VIX",
        "^VXN",
    ],
    "INDEXES": [
        "^GSPC",
        "^NDX",
        "^DJI",
        "^RUT",
        "^IXIC",
        "^STOXX50E",
        "^FTSE",
        "^GDAXI",
        "^FCHI",
        "^N225",
        "^HSI",
    ],
}


BENCHMARKS = {
    "QQQ": "SPY",
    "QQQM": "SPY",
    "QQQJ": "QQQ",
    "QQQI": "QQQ",
    "QQQY": "QQQ",
    "QYLD": "QQQ",
    "JEPQ": "QQQ",
    "QLD": "QQQ",
    "TQQQ": "QQQ",
    "PSQ": "QQQ",
    "QID": "QQQ",
    "SQQQ": "QQQ",
    "SMH": "QQQ",
    "SOXX": "QQQ",
    "XLK": "SPY",
    "IWM": "SPY",
    "RSP": "SPY",
    "TLT": "IEF",
    "GLD": "SPY",
}


DEALER_ENGINE_IMPLEMENTADO = {
    "QQQ",
}